config/routes.rb
Sms::Application.routes.draw do
  

  devise_for :users, :controllers => { :registrations => "user/registrations" }
	
	namespace "institution" do
		resources :institutes, :institution_groups
	end

	namespace "user" do 
		resources :user_roles_map do 
			collection do
				get 'user_roles_mapping'
				get 'load_user_roles'
				post 'save_user_roles'
			end
		end

		resources :roles do 
		end
		
		resources :address, :country
	end
	

	namespace "menu" do
		resources :mappings do 
			collection do
				get 'role_menu_group'
				post 'role_menu_group_save'
				get 'menu_group_containers'
				get 'menu_container'
				get 'menu_group_containers_mapping_page'
				post 'menu_group_containers_mapping_page_save'
				get 'menu_container_links'
				get 'menu_container_links_mapping_page'
				post 'menu_container_links_mapping_page_save'
				get 'module_links'
			end
		end

		resources :groups, :container

	end

  namespace :menu do 
    resources :mappings do 
      collection do
        get 'menu_group_menu_containers'
        get 'menu_container_menu_groups'
      end
    end
		
		resources :links do 
			collection do
				get 'load_links'
			end
		end

		resources :modules do 
			collection do
				get 'load_modules'
			end
		end		 
  end
		
	namespace :student do
		resources :students do
			collection do
				get 'student_registration'
			end
		end	
	end
  
  namespace "hostel" do
	end

  namespace "library" do
	end

  namespace "report" do
	end

  namespace "bills" do
	end

  resources :home do
    collection do
      get 'login'
			get 'selectrole'
			get 'adminpage'
			get 'set_logged_role'
			get 'userpage'
   end
  
  end

	root :to => "home#index"

end

app/models/address.rb
# phone                   	 int(11)      
# street                  	 varchar(255) 
# place                   	 varchar(255) 
# state                   	 text         
# country                 	 text         
# narration	                 text
class Address < ActiveRecord::Base
	belongs_to :user_id
end

app/models/country.rb
class Country < ActiveRecord::Base
	validates_uniqueness_of :name, {:message => "Country name Already Exist.. :(" }
	validates_presence_of :name
	before_validation :capitalize_name
	
	def capitalize_name
		self.name=self.name.upcase
	end

end

app/models/degree.rb
class Degree < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :location  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :personnel
  has_many :employee_experiences
  has_many :education_details
  has_many :employee_family_details
  has_many :employee_bank_details
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/job_grade.rb
class JobGrade < ActiveRecord::Base
end

app/models/leave_type.rb
class LeaveType < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/menu_group.rb
class MenuGroup < ActiveRecord::Base
	has_many :menu_group_menu_container
	has_many :menu_containers, :through => :menu_group_menu_container
	belongs_to :role
#	named_scope :active, 
end

app/models/menu_link.rb
class MenuLink < ActiveRecord::Base

  belongs_to :module_context
  belongs_to :menu_groups, :through => :menu_container
  
  
	before_save :upcase_mathod, :capitalize_name
  before_create :add_path

	def upcase_mathod	
		self.method = self.method.upcase
  end

  def capitalize_name 
    self.name = self.name.capitalize
  end 
	
	def add_path
		self.path = self.path.to_s + "_path"
  end
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
  has_one :employee
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/role.rb
# name        varchar(255) 
# priority    int(11)    

class Role < ActiveRecord::Base

	before_save :capitalise_mathod
	has_many :users_roles
	has_many :users, :through => :users_roles
	has_one :menu_group

	named_scope :active, { :conditions => {:status => true } }

	def capitalise_mathod	
		self.name = self.name.capitalize
	end

	def root_path
		return '/'+self.controller+'/'+self.action
	end
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/title.rb
class Title < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
	
	has_many :users_roles, :dependent => :delete_all
	has_many :roles, :through => :users_roles
	has_one :personnel
	#validates :fullname, :length => { :maximum => 40 }
  #validates :shortbio, :length => { :maximum => 500 }
#	current_user.update_attribute :admin, true
	
	def is_admin?
		status= false
		self.roles.each do |role|
			if role.name == 'Admin'
			 status=true
			end
		end
		return status
	end	

	def self.activate_admin(email)
		current_user=User.find_by_email(email)
		admin_role=Role.active.find_by_name('Admin')
		@ur=UsersRole.new
		@ur.user_id=current_user
		@ur.role_id=admin_role
		@ur.status=true
		if @ur.save!
				puts "Admin created...."
		else
				puts "Admin Not created...."
		end
	end
end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sms</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
  
</head>
<body class='body' height= "100%">
	<div id='page'>
		<div id='header'><%= render :partial => "layouts/header" %></div>
	
		<div id='top_menu'></div>

		<div id='container'>
			<div id='left_menu'><%= render :partial=> "layouts/leftmenu" %></div>
			<div id='center_container'>
				<div class="load_notice"><%= flash[:notice] %></div>
				<div id="load_page"></div>
				<%= yield %>
			</div>

		</div>		
		<div id='footer'><%= render :partial => "layouts/footer"%></div>
	</div>
</body>
</html>

app/views/layouts/index.html.erb
 This is Home page of sms 	<br>


<%= link_to "Role1 ", user_roles_path %><br>
<%= link_to "Role2 ", user_country_index_path %>

app/views/layouts/selectrole.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sms</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
  
</head>
<body class='body' height= "100%">
	<div id='page'>
		<div id='header'><%= render :partial => "layouts/header" %></div>
	
		<div id='top_menu'></div>

		<div id='container'>
		<% if user_signed_in? && current_user.is_admin? %>			
			
		<% else
		end %>
			<div id='center_container'>
				<div class="load_notice"><%= flash[:notice] %></div>
				<div id="load_page"></div>
				<%= yield %>
			</div>

		</div>		
		<div id='footer'><%= render :partial => "layouts/footer"%></div>
	</div>
</body>
</html>